CREATE TABLE IF NOT EXISTS DB_COMIC_EPISODE_OBJECT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMIC_ID TEXT,
    EPISODE_ID TEXT,
    EPISODE_ORDER INTEGER,
    TITLE TEXT,
    TOTAL INTEGER,
    UPDATED_AT TEXT
);

INSERT INTO DB_COMIC_EPISODE_OBJECT (
    COMIC_ID,
    EPISODE_ID,
    EPISODE_ORDER,
    TITLE,
    TOTAL,
    UPDATED_AT
)
SELECT
    COMIC_ID,
    EPISODE_ID,
    EPISODE_ORDER,
    TITLE,
    TOTAL,
    UPDATED_AT
FROM DOWNLOAD_COMIC_EPISODE_OBJECT
WHERE STATUS = 0;

DELETE FROM DOWNLOAD_COMIC_EPISODE_OBJECT WHERE STATUS = 0;
