CREATE TABLE IF NOT EXISTS DB_COMIC_EPISODE_OBJECT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMIC_ID TEXT,
    EPISODE_ID TEXT,
    EPISODE_ORDER INTEGER,
    TITLE TEXT,
    TOTAL INTEGER,
    UPDATED_AT TEXT
);

INSERT INTO DB_COMIC_EPISODE_OBJECT (
    COMIC_ID,
    EPISODE_ID,
    EPISODE_ORDER,
    TITLE,
    TOTAL,
    UPDATED_AT
)
SELECT
    COMIC_ID,
    EPISODE_ID,
    EPISODE_ORDER,
    TITLE,
    TOTAL,
    UPDATED_AT
FROM DOWNLOAD_COMIC_EPISODE_OBJECT
WHERE STATUS = 0;

DELETE FROM DOWNLOAD_COMIC_EPISODE_OBJECT WHERE STATUS = 0;

UPDATE DB_COMIC_DETAIL_OBJECT
SET DOWNLOAD_STATUS = 0,
    DOWNLOADED_AT = 0
WHERE DOWNLOAD_STATUS > 0
  AND COMIC_ID NOT IN (
      SELECT DISTINCT COMIC_ID
      FROM DOWNLOAD_COMIC_EPISODE_OBJECT
      WHERE COMIC_ID IS NOT NULL
  );

UPDATE DB_COMIC_DETAIL_OBJECT
SET DOWNLOAD_STATUS = 1
WHERE COMIC_ID IN (
    SELECT DISTINCT COMIC_ID
    FROM DOWNLOAD_COMIC_EPISODE_OBJECT
    WHERE STATUS != 4
      AND COMIC_ID IS NOT NULL
);

UPDATE DB_COMIC_DETAIL_OBJECT
SET DOWNLOAD_STATUS = 4,
    DOWNLOADED_AT = CASE
        WHEN DOWNLOADED_AT > 0 THEN DOWNLOADED_AT
        ELSE CAST(strftime('%s', 'now') AS INTEGER) * 1000
    END
WHERE COMIC_ID IN (
    SELECT COMIC_ID
    FROM DOWNLOAD_COMIC_EPISODE_OBJECT
    WHERE COMIC_ID IS NOT NULL
    GROUP BY COMIC_ID
    HAVING COUNT(*) > 0
       AND SUM(CASE WHEN STATUS != 4 THEN 1 ELSE 0 END) = 0
);
