package com.picacomic.fregata;

import android.content.Context;
import android.app.Activity;
import android.app.Application;
import android.os.Bundle;

import coil.Coil;
import coil.disk.DiskCache;
import coil.ImageLoader;
import coil.ImageLoaderFactory;
import coil.request.CachePolicy;

import com.orm.SugarApp;
import com.picacomic.fregata.b.b;
import com.picacomic.fregata.utils.NetworkSecurityHelper;
import com.picacomic.fregata.utils.ThemeColorHelper;
import com.picacomic.fregata.utils.d;
import com.picacomic.fregata.utils.e;
import com.picacomic.fregata.utils.f;
import com.picacomic.fregata.utils.LauncherIconHelper;

import java.io.File;

import okhttp3.OkHttpClient;

/* JADX INFO: loaded from: classes.dex */
public class MyApplication extends SugarApp implements ImageLoaderFactory {
    public static final String TAG = "MyApplication";
    private static MyApplication hk;
    private static Context mAppContext;
    private d hl;
    private int startedActivityCount;
    private boolean wasBackgrounded;
    private boolean lockOnNextResume;

    // Key2 from picacomic_downloader (d.py)
    private static final String HMAC_KEY = "~d}$Q7$eIni=V)9\\RK/P.RM4;9[7|@/CA}b~OW!3?EV`:<>M7pddUBL5n|0/*Cn";

    /**
     * 对应 native getStringSigFromNative()
     * 返回 HMAC 密钥 Key2
     */
    public String getStringSigFromNative() {
        return HMAC_KEY;
    }

    /**
     * 对应 native getStringConFromNative(String[])
     * 签名 raw 串: url + time + nonce + method + apiKey
     * strArr = [baseUrl, strippedUrl, time, nonce, method, apiKey, version, buildVersion]
     */
    public String getStringConFromNative(String[] strArr) {
        if (strArr == null || strArr.length < 6) {
            return "";
        }
        return strArr[1] + strArr[2] + strArr[3] + strArr[4] + strArr[5];
    }

    /**
     * 对应 native getStringComFromNative()
     */
    public String getStringComFromNative() {
        return "1";
    }

    static {
        androidx.appcompat.app.AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
    }

    @Override // com.orm.SugarApp, android.app.Application
    public void onCreate() {
        super.onCreate();
        androidx.appcompat.app.AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
        hk = this;
        s(getApplicationContext());
        LauncherIconHelper.syncLauncherIcon(this);
        setTheme(ThemeColorHelper.resolveLegacyThemeResId(this));
        registerActivityLifecycleCallbacks(new ActivityLifecycleCallbacks() {
            @Override public void onActivityStarted(Activity activity) {
                if (startedActivityCount++ == 0 && wasBackgrounded) {
                    lockOnNextResume = true;
                    wasBackgrounded = false;
                }
            }
            @Override public void onActivityStopped(Activity activity) {
                if (startedActivityCount > 0 && --startedActivityCount == 0) {
                    wasBackgrounded = true;
                }
            }
            @Override public void onActivityCreated(Activity a, Bundle b) { }
            @Override public void onActivityResumed(Activity a) { }
            @Override public void onActivityPaused(Activity a) { }
            @Override public void onActivitySaveInstanceState(Activity a, Bundle b) { }
            @Override public void onActivityDestroyed(Activity a) { }
        });
    }

    /** Returns and clears the lock request generated by a real app background transition. */
    public synchronized boolean consumeLockOnNextResume() {
        boolean result = lockOnNextResume;
        lockOnNextResume = false;
        return result;
    }

    public static synchronized void refreshCoilImageLoader() {
        if (mAppContext == null) {
            return;
        }
        Coil.setImageLoader((ImageLoaderFactory) () -> createCoilImageLoader(mAppContext));
    }

    @Override
    public ImageLoader newImageLoader() {
        return createCoilImageLoader(mAppContext != null ? mAppContext : this);
    }

    private static ImageLoader createCoilImageLoader(Context context) {
        return new ImageLoader.Builder(context)
                .okHttpClient(createImageOkHttpClientBuilder(context).build())
                .diskCache(() -> new DiskCache.Builder()
                        .directory(new File(context.getCacheDir(), "coil_cache"))
                        .maxSizeBytes(resolveCoilCacheMaxSizeBytes(context))
                        .build())
                .memoryCachePolicy(CachePolicy.ENABLED)
                .diskCachePolicy(CachePolicy.ENABLED)
                .networkCachePolicy(CachePolicy.ENABLED)
                .respectCacheHeaders(false)
                .build();
    }

    private static long resolveCoilCacheMaxSizeBytes(Context context) {
        int cacheSizeMb = e.ar(context);
        if (cacheSizeMb <= 0) {
            cacheSizeMb = 128;
        }
        return cacheSizeMb * 1024L * 1024L;
    }

    private static OkHttpClient.Builder createImageOkHttpClientBuilder(Context context) {
        OkHttpClient.Builder builder = new OkHttpClient.Builder().dns(new b());
        NetworkSecurityHelper.applySslPolicy(builder, context);
        return builder;
    }

    public static MyApplication bx() {
        return hk;
    }

    public static Context by() {
        return mAppContext;
    }

    public void s(Context context) {
        mAppContext = context;
    }

    public boolean bz() {
        StringBuilder sb = new StringBuilder();
        sb.append(getStringComFromNative());
        sb.append("");
        return sb.toString().equalsIgnoreCase("1");
    }

    public String c(String[] strArr) {
        if (this.hl == null) {
            this.hl = new d();
        }
        String str = "";
        for (String str2 : strArr) {
            str = str + str2 + ", ";
        }
        f.D(TAG, "RAW parameters = " + str);
        String stringConFromNative = getStringConFromNative(strArr);
        f.D(TAG, "CONCAT parameters = " + stringConFromNative);
        f.D(TAG, "CONCAT KEY = " + getStringSigFromNative());
        return this.hl.C(stringConFromNative, getStringSigFromNative());
    }
}
